# Generated by Django 5.1.4 on 2025-01-13 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="data_publicacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
